spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dai-blog?useUnicode=true&characterEncoding=gbk&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  devtools:
    restart:
      enabled: false
  application:
    name: dai-blog

